version: '2.4'

services:
  git-mirror:
    build: .
    environment:
      MIRROR:
      ORIGIN:
      PRIVATE_KEY:
    image: interaction/git-mirror:${IMAGE_TAG:-local}
    volumes:
      - ./git-mirror.sh:/etc/periodic/15min/git-mirror
